name: watinee
favicon: null
layout_spectrum: 0.34770221170037985
typography_spectrum: 0.2782456453423947
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8353178212419152
  lightness: 0.749910386512056
  saturation: 0.07911111880093813
  rhythmicContrast: 0.4074872019700706
purpose: []
